from __future__ import annotations

from pathlib import Path
from typing import Any

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[2] / "generated_assets" / "interiors"


def _coerce_page_count(raw_pages: Any, default: int = 1) -> int:
    if isinstance(raw_pages, int):
        return max(1, raw_pages)
    if isinstance(raw_pages, str):
        digits = "".join(ch for ch in raw_pages if ch.isdigit())
        if digits:
            return max(1, int(digits))
    return default


def _draw_journal_template(pdf: canvas.Canvas, section_name: str, page_number: int) -> None:
    width, height = LETTER

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(72, height - 72, section_name)

    pdf.setFont("Helvetica", 9)
    pdf.drawRightString(width - 72, height - 72, f"Page {page_number}")

    y = height - 105
    for _ in range(28):
        pdf.line(72, y, width - 72, y)
        y -= 22


def generate_interior_pdf(sections: list[dict[str, Any]], output_name: str) -> str:
    """Generate a deterministic journal interior PDF and return file path."""
    if not sections:
        raise ValueError("Cannot generate interior PDF without content sections")

    DEFAULT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = DEFAULT_OUTPUT_DIR / f"{output_name}.pdf"

    pdf = canvas.Canvas(str(output_path), pagesize=LETTER)
    width, height = LETTER

    # Title page
    pdf.setFont("Helvetica-Bold", 30)
    pdf.drawCentredString(width / 2, height - 220, "Journal Interior")
    pdf.setFont("Helvetica", 12)
    pdf.drawCentredString(width / 2, height - 250, "Generated by ForgeAI")
    pdf.showPage()

    template_page_number = 1
    for section in sections:
        section_name = str(section.get("name") or "Untitled Section")
        section_purpose = str(section.get("purpose") or "")
        section_pages = _coerce_page_count(section.get("pages"), default=1)

        # Section header page
        pdf.setFont("Helvetica-Bold", 22)
        pdf.drawString(72, height - 120, section_name)
        pdf.setFont("Helvetica", 12)
        pdf.drawString(72, height - 150, f"Purpose: {section_purpose}")
        pdf.showPage()

        # Repeated journal template pages for each section
        for _ in range(section_pages):
            _draw_journal_template(pdf, section_name=section_name, page_number=template_page_number)
            template_page_number += 1
            pdf.showPage()

    pdf.save()
    return str(output_path)
